config/routes.rb
Test1::Application.routes.draw do
 

  resources :users do
    get :following
  end
  resources :sessions, only: [:new, :create, :destroy]
  resources :ideas, only: [:create, :destroy, :show]
  resources :followships, only: [:create, :destroy]
  resources :brands, only: [:create, :destroy, :show, :new, :edit, :update, :index]

  match '/signup',  to: 'users#new'
  match '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete

  root to: 'static_pages#home'

  get "static_pages/home"  
  get "static_pages/about"
  get "static_pages/admin"
  match '/admin',  to: 'static_pages#admin'

end

app/models/idea.rb
class Idea < ActiveRecord::Base
  attr_accessible :content, :brand_id
  belongs_to :user

  has_many :reverse_followships, foreign_key: "followed_idea_id",
           class_name:  "Followship",
           dependent:   :destroy
  has_many :followers, through: :reverse_followships, source: :follower

  validates :content, presence: true, length: { maximum: 500 }
  validates :user_id, presence: true
  validates :brand_id, presence: true
  default_scope order: 'ideas.created_at DESC'

  def self.popular

   Idea.find_by_sql("SELECT * FROM ideas
  INNER JOIN followships ON ideas.id = followships.followed_idea_id
  WHERE followships.followed_idea_id.count > 3
  ORDER ideas.created_at desc")

  end
 
end

app/controllers/ideas_controller.rb
class IdeasController < ApplicationController
  before_filter :signed_in_user,     only: [:destroy, :create, :new]
  before_filter :admin_user,     only: [:destroy]

  def create
    @idea = current_user.ideas.build(params[:idea])
    @brand = Brand.find(params[:brand_id])
    @idea.brand_id = @brand.id
   
	
    if @idea.save
      flash[:success] = "Idea created!"
      redirect_to @brand
    else
      @feed_items = []
      redirect_to @brand
    end
  end

  def destroy
    Idea.find(params[:id]).destroy
    flash[:success] = "Idea destroyed."
    redirect_to brands_path
  end

  def show
    @idea = Idea.find(params[:id])
    @brand = Brand.find(@idea.brand_id)
    @user = User.find(@idea.user_id)
  end
	private
	 	def admin_user
        	redirect_to(root_path) unless current_user.admin?
      		end
end

app/helpers/ideas_helper.rb
module IdeasHelper

def facebook_like(idea_url)
            content_tag :iframe, nil, :src => "http://www.facebook.com/plugins/like.php?href=https://empowler.herokuapp.com#{idea_url}&layout=standard&show_faces=true&width=450&action=recommend&font=arial&colorscheme=light&height=80", :scrolling => 'no', :frameborder => '0', :allowtransparency => true, :id => :facebook_like
end


end

app/views/ideas/_form.html.erb
<%= form_for(@idea) do |f| %>
  <% if @idea.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@idea.errors.count, "error") %> prohibited this idea from being saved:</h2>

      <ul>
      <% @idea.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :content %><br />
    <%= f.text_field :content %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br />
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :followers %><br />
    <%= f.number_field :followers %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/ideas/_idea.html.erb

<td>
  
  <h4><%= idea.content %></h4>
  <span class="followers">  Supporters: <%= idea.followers.count %></span>
  <span class="timestamp"> Posted <%= time_ago_in_words(idea.created_at) %> ago. </span> 
  <p><b>Creada por:</b>
  <%=link_to idea.user.name, idea.user %>
  </p>	
  <% if current_user != nil %>
	<%=render :partial => 'users/follow_form',  :locals => {:idea => idea} %>
  <% else %>
	<h5><%=link_to "Resgistrate para unirte a esta idea!" , signup_path%></h5> </br>
  <% end %>
  </td>
  <td>
	</br>
  <%= tweet_button(:text => "Únete a mi idea! in @Empowler! #{idea.content}", :count => "horizontal", :related => "Empowler", :url => "https://empowler.herokuapp.com/#{url_for(idea)}") %>
 <%=render :partial => 'shared/fbshare',  :locals => {:idea => idea} %>
   <%if not current_user == nil%>
	
	<% if current_user.admin?%>
      | <%= link_to "delete idea", idea, method: :delete,
                    data: { confirm: "You sure?" } %>
  <% end %>
  <% end %>
  </td>
  


app/views/ideas/edit.html.erb
<h1>Editing idea</h1>

<%= render 'form' %>

<%= link_to 'Show', @idea %> |
<%= link_to 'Back', ideas_path %>

app/views/ideas/index.html.erb
<h1>Listing ideas</h1>

<table>
  <tr>
    <th>Content</th>
    <th>User</th>
    <th>Followers</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @ideas.each do |idea| %>
  <tr>
    <td><%= idea.content %></td>
    <td><%= idea.user_id %></td>
    <td><%= idea.followers %></td>
    <td><%= link_to 'Show', idea %></td>
    <td><%= link_to 'Edit', edit_idea_path(idea) %></td>
    <td><%= link_to 'Destroy', idea, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Idea', new_idea_path %>

app/views/ideas/new.html.erb
<h1>New idea</h1>

<%= render 'form' %>

<%= link_to 'Back', ideas_path %>

app/views/ideas/show.html.erb
<aside class="span3">
<p id="notice"><%= notice %></p>
<% if @brand.image? %>
		<%= image_tag @brand.image.url %>		
<%end%>
<%=link_to "Other ideas for ".concat(@brand.name) , brand_path(@brand)%>
</aside>
<aside>
</br>
<h3>  
  <%= @idea.content %>
</h3>
</br>
<p>
  <b>Supporters:</b>
  <%= @idea.followers.count %>
</p>
<p>
  <b>Creada por:</b>
  <%=link_to @user.name, @user %>
</p>

</br>
<h4>  
  Comparte y para apoyar esta misión!
</h4>
</br>
  <div><%= tweet_button(:via => "Empowler", :text => @idea.content, :count => "horizontal", :related => "Empowler") %></div>	
  <%= facebook_like(url_for(@idea)) %>
</aside>