config/routes.rb
Test1::Application.routes.draw do
 

  resources :users do
    get :following
  end
  resources :sessions, only: [:new, :create, :destroy]
  resources :ideas, only: [:create, :destroy, :show]
  resources :followships, only: [:create, :destroy]
  resources :brands, only: [:create, :destroy, :show, :new, :edit, :update, :index]

  match '/signup',  to: 'users#new'
  match '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete

  root to: 'static_pages#home'

  get "static_pages/home"  
  get "static_pages/about"
  get "static_pages/admin"
  match '/admin',  to: 'static_pages#admin'

end

app/views/shared/_bigbutton.html.erb

</br></br>
<a href = <%= url_for(brands_path)%> >
	<div class = "button">
   	<h3>Misiones</h3>	
	<p>Ve y crea las tuyas!</p>
	</div>
	</a>

app/views/shared/_brands_grid.html.erb
<div class="container1">


<%@popular_brands.each do |brand|%>
<div class="float1">
<div class="spacer1">
  &nbsp;
</div>
  <% if brand.image? %>	
	<%= link_to (image_tag brand.image.url(:mini)), 
        url_for({:controller => 'brands', :action => 'show', :id => brand.id}) %>
	<%end%>
  
</div>

<%end%>



</div>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
    <div id="error_explanation">
      <div class="alert alert-error">
        The form contains <%= pluralize(object.errors.count, "error") %>.
      </div>
      <ul>
        <% object.errors.full_messages.each do |msg| %>
            <li>* <%= msg %></li>
        <% end %>
      </ul>
    </div>
<% end %>

app/views/shared/_fbshare.html.erb
<fb:like href="https://empowler.herokuapp.com<%=url_for(idea)%>" send="true" layout="button_count" width="200" show_faces="false" action="like" font="lucida grande"></fb:like>

app/views/shared/_feed.html.erb
<% if @feed_items.any? %>
    <ul class="ideas">      
       <%@feed_items.each do |popular_idea|%>	
     <li id="<%= popular_idea.id %>"> 
     <%brand = Brand.find(popular_idea.brand_id)%>
       <% if brand.image? %>	
	<%= link_to (image_tag brand.image.url(:mini)), 
        url_for({:controller => 'brands', :action => 'show', :id => brand.id}) %>
	<%end%> 
     <span class="content"><h5><%=link_to popular_idea.content, url_for({:controller => 'ideas', :action => 'show', :id => popular_idea.id}) %></h5></span>    
    <span>
    Supporters:  <%= popular_idea.followers.count %>
   </span></br>  
   <span>   
   </li>

	<%end%>
    </ul>    
<% end %>

app/views/shared/_feed_item.html.erb

  <td><h3><%= feed_item.content %></h3>
       <h4>Friends aboard this mission:</h4> <h3><%= feed_item.followers.count %></h3>
       <span class="timestamp">
    	Posted <%= time_ago_in_words(feed_item.created_at) %>
  	</span> 
  </td>
  <td>	 
        <% if current_user != nil %>
	<%=render :partial => 'users/follow_form',  :locals => {:idea => feed_item} %>
  	<%end%> 
  </td>
  <td>
	  	<%= tweet_button(:via => "Empowler", :text => feed_item.content, :count => "horizontal", :related => 		"Empowler") %>	  
	 	 
	 	 <%= facebook_like(url_for(feed_item)) %> 
  </td>


app/views/shared/_following_stats.html.erb
<% @user ||= current_user %>
<div class="stats">
  <a href="<%= '#' %>">

    <strong id="following" class="stat">
      <%=  @user.followed_ideas.count %>
    </strong>
    followed ideas
  </a>
</div>

app/views/shared/_home_brands.html.erb
<li> 
<%if @popular_brands != nil%>
<%@popular_brands.each do |brand|%>
        <% if brand.image? %>	
	<%= link_to (image_tag brand.image.url(:mini)), 
        url_for({:controller => 'brands', :action => 'show', :id => brand.id}) %>
	<%end%>
<%end%>
<%end%>
</li>

app/views/shared/_ideas_form.html.erb
<%= form_for(@newidea) do |f| %>
    <%= render 'shared/error_messages', object: f.object %>
    <div class="field">
      <%= f.text_area :content, placeholder: "It would be great if  #{@brand.name}" %>
    </div>  
        
        <%= hidden_field_tag  'brand_id', params[:id] %>
    <%= f.submit "Share new idea!", class: "btn btn-large btn-primary" %>
<% end %>

app/views/shared/_popular_ideas.html.erb
<% if @popular_ideas.any? %>
    <ul class="ideas">
	
       <%@popular_ideas.each do |popular_idea|%>
     <li id="<%= popular_idea.id %>">  
	<%brand = Brand.find(popular_idea.brand_id)%>
       <% if brand.image? %>	
	<%= link_to (image_tag brand.image.url(:mini)), 
        url_for({:controller => 'brands', :action => 'show', :id => brand.id}) %>
	<%end%> 
     <span class="content"><h5><%=link_to popular_idea.content, url_for({:controller => 'brands', :action => 'show', :id => popular_idea.brand_id}) %></h5></span>    
    <span>
    Friends aboard:  <%= popular_idea.followers.count %>
   </span></br>  
   <span>   
   </li>
	<%end%>
    </ul>    
<% end %>

app/views/shared/_user_info.html.erb
<a href="<%= user_path(current_user) %>">
  <%= gravatar_for current_user, size: 52 %>
</a>
<h1>
  <%= current_user.name %>
</h1>
<span>
  <%= link_to "view my profile", current_user %>
</span>
<span>
  <%= pluralize(current_user.ideas.count, "idea") %>
</span>